//============================================================================
//  Copyright (c) Kitware, Inc.
//  All rights reserved.
//  See LICENSE.txt for details.
//
//  This software is distributed WITHOUT ANY WARRANTY; without even
//  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//  PURPOSE.  See the above copyright notice for more information.
//============================================================================

#ifndef vtk_m_filter_ImageDifference_h
#define vtk_m_filter_ImageDifference_h

#include <vtkm/TypeList.h>
#include <vtkm/filter/FilterField.h>

namespace vtkm
{
namespace filter
{

/// \brief Construct an ImageDifference of a given DataSet
///
/// The dataset generated by executing this filter is a Dataset with two Fields:
///   - "image-diff": Uniform Structured Dataset, difference values of image A - B
///   - "threshold-output": Uniform Structured Dataset, the magnitudes of the pixel differences
///
/// The threshold-output is calculated for each pixel using the `vtkm::Magnitude` vector function
/// on the individual pixel difference.
///
class ImageDifference : public vtkm::filter::FilterField<ImageDifference>
{
public:
  using SupportedTypes = vtkm::TypeListFieldVec4;

  VTKM_CONT ImageDifference();

  VTKM_CONT vtkm::IdComponent GetRadius() const { return this->Radius; }
  VTKM_CONT void SetRadius(const vtkm::IdComponent& radius) { this->Radius = radius; }

  VTKM_CONT vtkm::FloatDefault GetThreshold() const { return this->Threshold; }
  VTKM_CONT void SetThreshold(const vtkm::FloatDefault& threshold) { this->Threshold = threshold; }

  VTKM_CONT const bool& GetAveragePixels() const { return this->AveragePixels; }
  VTKM_CONT void SetAveragePixels(const bool& averagePixels)
  {
    this->AveragePixels = averagePixels;
  }

  VTKM_CONT const bool& GetImageDiffWithinThreshold() const
  {
    return this->ImageDiffWithinThreshold;
  }
  VTKM_CONT void SetThresholdFieldName(const std::string& name) { this->ThresholdFieldName = name; }
  VTKM_CONT const std::string& GetThresholdFieldName() const { return this->ThresholdFieldName; }

  /// Choose the primary field to operate on.  For Image difference A - B, A is the
  /// primary field.
  VTKM_CONT
  void SetPrimaryField(
    const std::string& name,
    vtkm::cont::Field::Association association = vtkm::cont::Field::Association::ANY)
  {
    this->SetActiveField(name, association);
  }

  VTKM_CONT const std::string& GetPrimaryFieldName() const { return this->GetActiveFieldName(); }
  VTKM_CONT vtkm::cont::Field::Association GetPrimaryFieldAssociation() const
  {
    return this->GetActiveFieldAssociation();
  }

  /// Choose the secondary field to operate on.  For Image difference A - B, B is the
  /// secondary field.
  VTKM_CONT
  void SetSecondaryField(
    const std::string& name,
    vtkm::cont::Field::Association association = vtkm::cont::Field::Association::ANY)
  {
    this->SecondaryFieldName = name;
    this->SecondaryFieldAssociation = association;
  }

  VTKM_CONT const std::string& GetSecondaryFieldName() const { return this->SecondaryFieldName; }
  VTKM_CONT vtkm::cont::Field::Association GetSecondaryFieldAssociation() const
  {
    return this->SecondaryFieldAssociation;
  }

  template <typename T, typename StorageType, typename DerivedPolicy>
  VTKM_CONT vtkm::cont::DataSet DoExecute(const vtkm::cont::DataSet& input,
                                          const vtkm::cont::ArrayHandle<T, StorageType>& primary,
                                          const vtkm::filter::FieldMetadata& fieldMetadata,
                                          vtkm::filter::PolicyBase<DerivedPolicy> policy);

private:
  vtkm::IdComponent Radius;
  vtkm::FloatDefault Threshold;
  bool AveragePixels;
  bool ImageDiffWithinThreshold;
  std::string SecondaryFieldName;
  vtkm::cont::Field::Association SecondaryFieldAssociation;
  std::string ThresholdFieldName;
};

} // namespace filter
} // namespace vtkm

#include <vtkm/filter/ImageDifference.hxx>

#endif // vtk_m_filter_ImageDifference_h
